// Locale JSON files are the source of truth. No runtime I/O or network translation is needed.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const zh = JSON.parse(fs.readFileSync(path.join(root, 'locales/zh-CN.json'), 'utf8'));
const en = JSON.parse(fs.readFileSync(path.join(root, 'locales/en.json'), 'utf8'));
const keys = Object.keys(zh).sort();
if (JSON.stringify(keys) !== JSON.stringify(Object.keys(en).sort())) throw new Error('Locale keys differ');
const placeholders = value => [...value.matchAll(/\{\d+\}/g)].map(m => m[0]).sort().join(',');
for (const key of keys) {
  if (typeof zh[key] !== 'string' || typeof en[key] !== 'string') throw new Error('Invalid locale value: ' + key);
  if (placeholders(zh[key]) !== placeholders(en[key])) throw new Error('Placeholder mismatch: ' + key);
}
const sourceRoot = path.join(root, 'entry/src/main/ets');
for (const file of fs.readdirSync(sourceRoot, { recursive: true }).filter(file => file.endsWith('.ets') && !file.endsWith('LocaleCatalog.ets'))) {
  const source = fs.readFileSync(path.join(sourceRoot, file), 'utf8');
  for (const match of source.matchAll(/\bt\(\s*("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')/g)) {
    const literal = match[1];
    const key = literal[0] === '"' ? JSON.parse(literal) : JSON.parse('"' + literal.slice(1, -1).replace(/\\'/g, "'").replace(/"/g, '\\"') + '"');
    if (!(key in zh)) throw new Error(`Missing message in ${file}: ${key}`);
  }
}
const ordered = source => Object.fromEntries(keys.map(key => [key, source[key]]));
const content = '// Generated by scripts/build-locales.cjs. Edit locales/*.json instead.\n' +
  'export const ZH_MESSAGES: Record<string, string> = ' + JSON.stringify(ordered(zh), null, 2) + ';\n' +
  'export const EN_MESSAGES: Record<string, string> = ' + JSON.stringify(ordered(en), null, 2) + ';\n';
const target = path.join(root, 'entry/src/main/ets/model/LocaleCatalog.ets');
if (process.argv.includes('--check')) {
  if (fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') !== content) throw new Error('Generated catalog is stale. Run node scripts/build-locales.cjs');
} else fs.writeFileSync(target, content);
console.log(`Validated ${keys.length} bilingual messages and their placeholders.`);
